### PR TITLE
May2020 Version: Expansion1 and 2 Files (In DLC Folder)

### PR DESCRIPTION
**Pull request by the-m4a**
The files in the DLC\Expansion1 and DLC\Expansion2 folders are currently the Fall 2019 version, this PR updates those files to the version packaged in the May 2020 update.

Files were copied from the _Civ6InstallLocation_\DLC\Expansion_x_\UI folder to the respective location in this repo

### CODE REVIEW

**Comment by the-m4a** [comment]
The history looks like a mess, because I had done the bad Git thing and made updates direct to my master branch before figuring out I needed to revert them.

Reading down on that list above, items 1 and 2 are undone by 3 and 4 respectively.

**Comment by alexeyOnGitHub** [comment]
if some commits revert changes from previous ones, we can just squash them into one and thus purge intermediate changes. 
does this PR affect any files from the previous PR https://github.com/civfanatics/Civ6-UIFiles/pull/1?  someone mentioned that file history was lost in that one.
it is not too late to either revert that PR or just drop the whole repo and re-fork it here, 
then re-submit both of these PRs - 1 and 2 (with files moved rather then added, or whatever makes sense).
@the-m4a  what do you think? I am fine with dropping the repo, re-forking it and then applying new PRs from you. only if that fixes the lost history issue in PR #1 though, otherwise there is no point..

we can easily squash commits in this PR #2 .

**Comment by the-m4a** [comment]
Yeah - the squash would be fine, no need to remake the fork.  There were 5 commits made by me for PR, 1 and 2 were reverted by 3 and 4, respectively, meaning that the changes in commit 5 are the only ones that matter. 

~~(If it’s 6 commits it’s because the change to the gossip/status box and the removal of the extra builder lens in the lens menu is commit 6)~~ confused my two PRs

**Comment by alexeyOnGitHub** [comment]
What about the previous pr? We can take care of the old history first

**Comment by the-m4a** [comment]
I was confusing the two PRs - will edit above.  Commit 5 with this PR is the only one that matters.  So all should be well. :)

The _other_ PR, which is trying to pull the CQUI changes into the civfanatics CQUI branch, that is the extra one I was thinking of earlier.

**Comment by alexeyOnGitHub** [comment]
here is the 1st PR that I meant:
https://github.com/civfanatics/Civ6-UIFiles/pull/1 
Place Expansion1 and Expansion2 with Files (Fall 2019 Expansion UI Files)

@alimulhuda had a valid concern [here](https://github.com/Azurency/CQUI_Community-Edition/issues/421#issuecomment-635670532). quoting his message:

> Right now if I go to https://github.com/civfanatics/Civ6-UIFiles/commits/expansion2/Replacements/WorldRankings.xml I can see it was changed a few times. If I go to the merged location here https://github.com/civfanatics/Civ6-UIFiles/commits/master/DLC/Expansion2/Replacements/WorldRankings.xml. It shows up as a new file. I can no longer look at the file in the new location and see the change log. Is there a way to see history from the new location in master without having to look back at the branch?

it is best to fix this now before merging anything else into the repo, if at all possible.
I will explore the folders structure myself too, I am not familiar with it

**Comment by alexeyOnGitHub** [comment]
created an issue where we can discuss this - https://github.com/civfanatics/Civ6-UIFiles/issues/3

**Comment by the-m4a** [comment]
Closing this - we will use alimulhuda's repo

**Pull request closed without merging**
